# ----------------------------------------------------------------------------
#
# Package             : openssl
# Source Repo         : https://github.com/openssl/openssl/
# Travis Job Link     : https://travis-ci.com/github/BalavvaMirji/openssl/builds/231638567
# Created travis.yml  : Yes
# Maintainer          : Balavva Mirji <Balavva.Mirji@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: Ruby
dest: focal
arch:
  - ppc64le
script:
  - ./config
  - make
  - sudo make install
  - make test
